# Generated by Django 4.2.30 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('scam_type', models.CharField(choices=[('phishing', 'Phishing'), ('fake_job', 'Fake Job'), ('catfish', 'Catfish'), ('investment', 'Investment Fraud'), ('shopping', 'Online Shopping'), ('tech_support', 'Tech Support'), ('other', 'Other')], max_length=50)),
                ('contact_used', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_count', models.IntegerField(default=0)),
                ('evidence_file', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
